import { ProfileData } from './types';

export const profileMockData: ProfileData = {
  userId: 'UID_123456789',
  username: '用户名',
  nickname: '用户名',
  walletAddress: '0x1234...5678',
  userRole: '普通用户',
  statusText: '账户状态正常',
  brief: '账户状态正常',
  gender: 'unknown',
  birthday: '',
  registerTime: '2024-01-15 10:30:00',
  email: 'user@example.com',
  phone: '+86 138****8888',
  emailVerified: true,
  phoneVerified: true,
  kycStatus: 'not_verified',
  merchantDepositStatus: 'not_applied',
  settings: {
    profilePublic: true,
    marketingEmails: false,
    transactionNotifications: true,
  },
  operationLogs: [
    {
      id: '1',
      createdAt: '2026-04-20 14:32:01',
      bizModule: 'profile',
      actionType: 'PROFILE_SAVE',
      summary: '保存个人基础资料',
      resultStatus: 'success',
    },
    {
      id: '2',
      createdAt: '2026-04-19 10:05:22',
      bizModule: 'security',
      actionType: 'EMAIL_VERIFY_SENT',
      summary: '发送邮箱验证邮件',
      resultStatus: 'success',
    },
    {
      id: '3',
      createdAt: '2026-04-18 09:12:00',
      bizModule: 'merchant',
      actionType: 'MERCHANT_TERMS_ACCEPT',
      summary: '确认商家入驻与保证金条款',
      resultStatus: 'success',
    },
    {
      id: '4',
      createdAt: '2026-04-17 16:40:00',
      bizModule: 'auth',
      actionType: 'LOGIN',
      summary: '账号登录（Web 管理端）',
      resultStatus: 'success',
    },
    {
      id: '5',
      createdAt: '2026-04-16 11:20:33',
      bizModule: 'deposit',
      actionType: 'DEPOSIT_INTENT_CREATE',
      summary: '创建保证金缴纳意图单',
      resultStatus: 'success',
    },
    {
      id: '6',
      createdAt: '2026-04-15 08:55:10',
      bizModule: 'kyc',
      actionType: 'KYC_SUBMIT',
      summary: '提交 KYC 认证资料',
      resultStatus: 'partial',
    },
    {
      id: '7',
      createdAt: '2026-04-10 19:01:00',
      bizModule: 'security',
      actionType: 'PHONE_BIND',
      summary: '绑定手机号',
      resultStatus: 'success',
    },
    {
      id: '8',
      createdAt: '2026-04-08 13:22:45',
      bizModule: 'profile',
      actionType: 'AVATAR_UPDATE',
      summary: '更新头像',
      resultStatus: 'failed',
    },
  ],
};
