import { ProfileData } from './types';

export const profileMockData: ProfileData = {
  userId: 'UID_123456789',
  username: 'username',
  nickname: 'username',
  walletAddress: '0x1234...5678',
  userRole: 'Standard user',
  statusText: 'Account is active',
  brief: 'Account is active',
  gender: 'unknown',
  birthday: '',
  registerTime: '2024-01-15 10:30:00',
  email: 'user@example.com',
  phone: '+86 138****8888',
  emailVerified: true,
  phoneVerified: true,
  kycStatus: 'not_verified',
  merchantDepositStatus: 'not_applied',
  settings: {
    profilePublic: true,
    marketingEmails: false,
    transactionNotifications: true,
  },
  operationLogs: [
    {
      id: '1',
      createdAt: '2026-04-20 14:32:01',
      bizModule: 'profile',
      actionType: 'PROFILE_SAVE',
      summary: 'Saved basic profile',
      resultStatus: 'success',
    },
    {
      id: '2',
      createdAt: '2026-04-19 10:05:22',
      bizModule: 'security',
      actionType: 'EMAIL_VERIFY_SENT',
      summary: 'Sent email verification',
      resultStatus: 'success',
    },
    {
      id: '3',
      createdAt: '2026-04-18 09:12:00',
      bizModule: 'merchant',
      actionType: 'MERCHANT_TERMS_ACCEPT',
      summary: 'Accepted merchant onboarding & deposit terms',
      resultStatus: 'success',
    },
    {
      id: '4',
      createdAt: '2026-04-17 16:40:00',
      bizModule: 'auth',
      actionType: 'LOGIN',
      summary: 'Account login (Web admin)',
      resultStatus: 'success',
    },
    {
      id: '5',
      createdAt: '2026-04-16 11:20:33',
      bizModule: 'deposit',
      actionType: 'DEPOSIT_INTENT_CREATE',
      summary: 'Created deposit payment intent',
      resultStatus: 'success',
    },
    {
      id: '6',
      createdAt: '2026-04-15 08:55:10',
      bizModule: 'kyc',
      actionType: 'KYC_SUBMIT',
      summary: 'Submitted KYC verification documents',
      resultStatus: 'partial',
    },
    {
      id: '7',
      createdAt: '2026-04-10 19:01:00',
      bizModule: 'security',
      actionType: 'PHONE_BIND',
      summary: 'Bound phone number',
      resultStatus: 'success',
    },
    {
      id: '8',
      createdAt: '2026-04-08 13:22:45',
      bizModule: 'profile',
      actionType: 'AVATAR_UPDATE',
      summary: 'Updated avatar',
      resultStatus: 'failed',
    },
  ],
};
