// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

import (
	"database/sql"
	"time"
)

type AddressListRequest struct {
	Level      int    `json:"level"`
	ParentCode string `json:"parent_code"`
}

type AddressListResponse struct {
	Addresses []*AddressNode `json:"address_node"`
}

type Address struct {
	ID           int64  `json:"id" `
	Code         string `json:"code" `
	Name         string `json:"name" `
	ParentCode   string `json:"parent_code" `
	Level        int    `json:"level" `
	ProvinceCode string `json:"province_code" `
	ProvinceName string `json:"province_name" `
	CityCode     string `json:"city_code" `
	CityName     string `json:"city_name" `
	DistrictCode string `json:"district_code" `
	DistrictName string `json:"district_name" `
	StreetCode   string `json:"street_code" `
	StreetName   string `json:"street_name" `
	FullAddress  string `json:"full_address" `
	Postcode     string `json:"post_code" `
	Sort         int    `json:"sort" gorm:"column:sort;type:int;default:0;comment:排序"`
	BaseModel
}

type AddressNode struct {
	Address  *Address
	Children []*AddressNode `json:"children,omitempty"` // 添加子节点字段，用于树形结构
}

type BaseModel struct {
	CreatedAt int64  `json:"createdAt" `
	UpdatedAt int64  `json:"updatedAt" `
	IsDeleted int    `json:"isDeleted" `
	Creator   string `json:"creator" `
	Updator   string `json:"updator" `
}

type UserAddressListRequest struct {
	UserID   int64  `json:"userId"`
	UserCode string `json:"userCode"`
}

type UserAddressListResponse struct {
	UserAddresses []*UserAddress `json:"user_addresses"`
}

type UserAddress struct {
	ID           int64        `json:"id"`            // 主键id
	UserID       int64        ` json:"userId"`       // 用户id
	UserCode     string       ` json:"userCode"`     // 用户编码
	ReciverName  string       ` json:"reciverName"`  // 收货人姓名
	ReciverPhone string       ` json:"reciverPhone"` // 手机号
	ProvinceCode string       ` json:"provinceCode"` // 省编码
	ProvinceName string       ` json:"provinceName"` // 省名称
	CityCode     string       `json:"cityCode"`      // 市编码
	CityName     string       `json:"cityName"`      // 市名称
	DistrictCode string       ` json:"districtCode"` // 区编码
	DistrictName string       `json:"districtName"`  // 区名称
	StreetCode   string       ` json:"streetCode"`   // 街道编码
	StreetName   string       ` json:"streetName"`   // 街道名称
	HouseAddress string       ` json:"houseAddress"` // 门牌号
	FullAddress  string       ` json:"fullAddress"`  // 完整地址
	IsDefault    int          ` json:"isDefault"`    // 是否默认
	Longitude    string       `json:"longitude"`     // 经度
	Latitude     string       ` json:"latitude"`     // 纬度
	CreatedAt    time.Time    `json:"createdAt" `
	UpdatedAt    time.Time    `json:"updatedAt" `
	DeletedAt    sql.NullTime `json:"DeletedAt" `
}

type UserAddressModifyRequest struct {
	ID           int64  `json:"id"`
	UserID       int64  `json:"userId"`       // 用户id
	UserCode     string `json:"userCode"`     // 用户编码
	ReciverName  string `json:"reciverName"`  // 收货人姓名
	ReciverPhone string `json:"reciverPhone"` // 手机号
	ProvinceCode string `json:"provinceCode"` // 省编码
	ProvinceName string `json:"provinceName"` // 省名称
	CityCode     string `json:"cityCode"`     // 市编码
	CityName     string `json:"cityName"`     // 市名称
	DistrictCode string `json:"districtCode"` // 区编码
	DistrictName string `json:"districtName"` // 区名称
	StreetCode   string `json:"streetCode"`   // 街道编码
	StreetName   string `json:"streetName"`   // 街道名称
	HouseAddress string `json:"houseAddress"` // 门牌号
	FullAddress  string `json:"fullAddress"`  // 完整地址
	IsDefault    int    `json:"isDefault"`    // 是否默认
	Longitude    string `json:"longitude"`    // 经度
	Latitude     string `json:"latitude"`     // 纬度
	IsDeleted    int    `json:"isDeleted"`    // 是否删除
	Creator      string `json:"creator"`      // 创建人
	Updator      string `json:"updator"`
}

type DeleteUserRequest struct {
	ID int64 `json:"id"`
}
