// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CategoryRequest struct {
	ID int64 `json:"id"`
}

type CategoryResponse struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type AttrGroupResponse struct {
	ID          uint           `json:"id"`
	Name        string         `json:"name"`
	Code        string         `json:"code"`
	Sort        int            `json:"sort"`
	Type        int            `json:"type"`
	Description string         `json:"description"`
	Status      int            `json:"status"`
	Attrs       []AttrResponse `json:"attrs"`
}

type AttrResponse struct {
	ID          uint   `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Type        int    `json:"type"`
	Status      int    `json:"status"`
	GroupID     uint   `json:"groupId"`
	Description string `json:"description"`
	Sort        int    `json:"sort"`
}

type CategoryTreeResponse struct {
	ID         uint                   `json:"id"`
	Name       string                 `json:"name"`
	Code       string                 `json:"code"`
	Level      int                    `json:"level"`
	Sort       int                    `json:"sort"`
	ParentID   uint                   `json:"parentId"`
	Icon       string                 `json:"icon"`
	AttrGroups []AttrGroupResponse    `json:"attrGroups,omitempty"`
	Children   []CategoryTreeResponse `json:"children,omitempty"`
}

type CategoryModifyRequest struct {
	ID         uint   `json:"id"`
	Name       string `json:"name"`
	Code       string `json:"code"`
	Sort       int    `json:"sort"`
	ParentID   uint   `json:"parentId"`
	ParentCode string `json:"parentCode"`
	Level      int    `json:"level"`
	Icon       string `json:"icon"`
	Status     int    `json:"status"`
}
