// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type HealthCheckReq struct {
	Service string `json:"service"`
}

type HealthCheckResp struct {
	Status string `json:"status"`
	Time   int64  `json:"time"`
}

type VersionReq struct {
}

type VersionResp struct {
	Version   string `json:"version"`
	BuildTime string `json:"build_time"`
	GitCommit string `json:"git_commit"`
	GoVersion string `json:"go_version"`
}
