// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type CreateProductReq struct {
	CreatorId     string `json:"creator_id"`
	TitleEn       string `json:"title_en"`
	TitleZh       string `json:"title_zh"`
	DescriptionEn string `json:"description_en"`
	DescriptionZh string `json:"description_zh"`
	Price         string `json:"price"`
	Category      string `json:"category"`
	IpfsHash      string `json:"ipfs_hash"`
	Inventory     int64  `json:"inventory"`
}

type CreateProductResp struct {
	Code        int         `json:"code"`
	Msg         string      `json:"msg"`
	ProductInfo ProductInfo `json:"product_info"`
}

type DeleteAttrGroupReq struct {
	ID uint `path:"id"` // 属性组ID
}

type DeleteAttrReq struct {
	ID uint `path:"id"` // 属性ID
}

type DeleteCategoryReq struct {
	ID uint `path:"id"` // 目录ID
}

type GetCategoryTreeReq struct {
	CategoryType int `path:"category_type"`
}

type GetNonceByAddressReq struct {
	WalletAddress string `path:"wallet_address"`
}

type GetNonceByAddressResp struct {
	Nonce string `json:"nonce"`
}

type HealthCheckReq struct {
	Service string `json:"service"`
}

type HealthCheckResp struct {
	Status string `json:"status"`
	Time   int64  `json:"time"`
}

type LoginReq struct {
	WalletAddress string `json:"wallet_address"`
	Signature     string `json:"signature"`
}

type LoginResp struct {
	Token    string   `json:"token"`
	UserInfo UserInfo `json:"user_info"`
}

type ProductInfo struct {
	Id            string `json:"id"`
	CreatorId     string `json:"creator_id"`
	TitleEn       string `json:"title_en"`
	TitleZh       string `json:"title_zh"`
	DescriptionEn string `json:"description_en"`
	DescriptionZh string `json:"description_zh"`
	Price         string `json:"price"`
	Category      string `json:"category"`
	Status        string `json:"status"`
	IpfsHash      string `json:"ipfs_hash"`
	Inventory     int64  `json:"inventory"`
	SalesCount    int64  `json:"sales_count"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
}

type ReviewProductReq struct {
	ProductId     string `json:"product_id"`
	Status        string `json:"status"`
	ReviewComment string `json:"review_comment"`
}

type ReviewProductResp struct {
	Code        int         `json:"code"`
	Msg         string      `json:"msg"`
	ProductInfo ProductInfo `json:"product_info"`
}

type SaveAttrGroupReq struct {
	ID            uint   `json:"id,optional"`          // 属性组ID，为0或空表示新增，有值表示编辑
	CategoryID    uint   `json:"categoryId,optional"`  // 目录ID
	AttrGroupName string `json:"attrGroupName"`        // 属性组名称
	AttrGroupCode string `json:"attrGroupCode"`        // 属性组编码
	Type          int    `json:"type,optional"`        // 类型：0=通用 1=目录专用
	Status        int    `json:"status,optional"`      // 状态：0=启用 1=禁用
	Sort          int    `json:"sort"`                 // 排序
	Description   string `json:"description,optional"` // 描述
}

type SaveAttrReq struct {
	ID            uint   `json:"id,optional"`          // 属性ID，为0或空表示新增，有值表示编辑
	AttrGroupID   uint   `json:"attrGroupId"`          // 属性组ID
	AttrGroupCode string `json:"attrGroupCode"`        // 属性组编码
	AttrName      string `json:"attrName"`             // 属性名称
	AttrCode      string `json:"attrCode"`             // 属性编码
	AttrType      int    `json:"attrType,optional"`    // 属性类型：1=文本 2=数字
	Status        int    `json:"status,optional"`      // 状态：0=启用 1=禁用
	Sort          int    `json:"sort"`                 // 排序
	Description   string `json:"description,optional"` // 描述
}

type SaveCategoryReq struct {
	ID         uint   `json:"id,optional"`         // 目录ID，为0或空表示新增，有值表示编辑
	Name       string `json:"name"`                // 目录名称
	Code       string `json:"code"`                // 目录编码
	ParentID   uint   `json:"parentId,optional"`   // 父目录ID
	ParentCode string `json:"parentCode,optional"` // 父目录编码
	Level      int    `json:"level,optional"`      // 层级
	Sort       int    `json:"sort"`                // 排序
	Icon       string `json:"icon,optional"`       // 图标
	MenuType   int    `json:"menuType"`            // 目录类型：0=商品目录 1=菜单目录
}

type UserInfo struct {
	Id        int64    `json:"id"`
	Address   string   `json:"address"`
	Nickname  string   `json:"nickname"`
	Avatar    string   `json:"avatar"`
	Status    int      `json:"status"`
	Roles     []string `json:"roles"`
	CreatedAt string   `json:"created_at"`
	UpdatedAt string   `json:"updated_at"`
}

type VersionResp struct {
	Version   string `json:"version"`
	BuildTime string `json:"build_time"`
	GitCommit string `json:"git_commit"`
	GoVersion string `json:"go_version"`
}
