// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type GetUserInfoReq struct {
	UserId string `json:"user_id"`
}

type GetUserInfoResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}
