// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	common "sapphire-mall/internal/handler/common"
	product "sapphire-mall/internal/handler/product"
	user "sapphire-mall/internal/handler/user"
	"sapphire-mall/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RespMiddleware},
			[]rest.Route{
				{
					// 获取导航目录结构
					Method:  http.MethodGet,
					Path:    "/:category_type/categories",
					Handler: common.GetCategoryTreeHandler(serverCtx),
				},
				{
					// 获取随机数
					Method:  http.MethodGet,
					Path:    "/:wallet_address/nonce",
					Handler: common.GetNonceByAddressHandler(serverCtx),
				},
				{
					// 健康检查
					Method:  http.MethodGet,
					Path:    "/health",
					Handler: common.HealthCheckHandler(serverCtx),
				},
				{
					// 登录
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: common.LoginHandler(serverCtx),
				},
				{
					// 获取版本信息
					Method:  http.MethodGet,
					Path:    "/version",
					Handler: common.GetVersionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/common"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RespMiddleware},
			[]rest.Route{
				{
					// 查询产品详细信息
					Method:  http.MethodPost,
					Path:    "/getProductDetails",
					Handler: product.GetProductDetailsHandler(serverCtx),
				},
				{
					// 分页查询多个产品
					Method:  http.MethodPost,
					Path:    "/products",
					Handler: product.ProductsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.RespMiddleware},
			[]rest.Route{
				{
					// 获取用户信息
					Method:  http.MethodGet,
					Path:    "/info/:user_id",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/user"),
	)
}
