// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	common "sapphire-mall/app/internal/handler/common"
	user "sapphire-mall/app/internal/handler/user"
	"sapphire-mall/app/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.RespMiddleware},
			[]rest.Route{
				{
					// 健康检查
					Method:  http.MethodGet,
					Path:    "/health",
					Handler: common.HealthCheckHandler(serverCtx),
				},
				{
					// 获取版本信息
					Method:  http.MethodGet,
					Path:    "/version",
					Handler: common.GetVersionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/common"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.RespMiddleware},
			[]rest.Route{
				{
					// 获取用户信息
					Method:  http.MethodGet,
					Path:    "/info/:user_id",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/user"),
	)
}
