// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type BaseResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type CreateProductReq struct {
	CreatorId     string `json:"creator_id"`
	TitleEn       string `json:"title_en"`
	TitleZh       string `json:"title_zh"`
	DescriptionEn string `json:"description_en"`
	DescriptionZh string `json:"description_zh"`
	Price         string `json:"price"`
	Category      string `json:"category"`
	IpfsHash      string `json:"ipfs_hash"`
	Inventory     int64  `json:"inventory"`
}

type CreateProductResp struct {
	Code        int         `json:"code"`
	Msg         string      `json:"msg"`
	ProductInfo ProductInfo `json:"product_info"`
}

type GetCategoryTreeReq struct {
	CategoryType int `path:"category_type"`
}

type GetNonceByAddressReq struct {
	WalletAddress string `path:"wallet_address"`
}

type GetNonceByAddressResp struct {
	Nonce string `json:"nonce"`
}

type GetProductReq struct {
	ProductId   int64  `json:"product_id"`
	ProductCode string `json:"product_code"`
}

type GetProductResp struct {
	Code        int         `json:"code"`
	Msg         string      `json:"msg"`
	ProductInfo ProductInfo `json:"product_info"`
}

type GetUserInfoReq struct {
	UserId int64 `path:"user_id"`
}

type GetUserInfoResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}

type HealthCheckReq struct {
	Service string `json:"service"`
}

type HealthCheckResp struct {
	Status string `json:"status"`
	Time   int64  `json:"time"`
}

type ListProductsReq struct {
	CategoryCodes string `json:"categoryCodes"` // 分类编码，多个用逗号分隔
	ProductName   string `json:"productName"`   // 商品名称
	Page          int    `json:"page"`          // 页码
	PageSize      int    `json:"pageSize"`      // 每页数量
}

type ListProductsResp struct {
	Code     int           `json:"code"`
	Msg      string        `json:"msg"`
	Products []ProductInfo `json:"products"`
	Total    int64         `json:"total"`
}

type LoginReq struct {
	WalletAddress string `json:"wallet_address"`
	Signature     string `json:"signature"`
}

type LoginResp struct {
	Token  string `json:"token"`
	UserId string `json:"user_id"`
}

type ProductInfo struct {
	Id            string `json:"id"`
	CreatorId     string `json:"creator_id"`
	TitleEn       string `json:"title_en"`
	TitleZh       string `json:"title_zh"`
	DescriptionEn string `json:"description_en"`
	DescriptionZh string `json:"description_zh"`
	Price         string `json:"price"`
	Category      string `json:"category"`
	Status        string `json:"status"`
	IpfsHash      string `json:"ipfs_hash"`
	Inventory     int64  `json:"inventory"`
	SalesCount    int64  `json:"sales_count"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
}

type ReviewProductReq struct {
	ProductId     string `json:"product_id"`
	Status        string `json:"status"`
	ReviewComment string `json:"review_comment"`
}

type ReviewProductResp struct {
	Code        int         `json:"code"`
	Msg         string      `json:"msg"`
	ProductInfo ProductInfo `json:"product_info"`
}

type VersionResp struct {
	Version   string `json:"version"`
	BuildTime string `json:"build_time"`
	GitCommit string `json:"git_commit"`
	GoVersion string `json:"go_version"`
}
